Feature/update readme
GAndriyS/munchkin_cardbase pull request #1
Opened 2017-01-17 23:03 UTC by GAndriyS

update repo readme file

2017-01-18 09:37 UTC, vira-lytvyn requested changes
Please add a license file to your project. This is compulsory for a project(open source inclusively) to have a license.

2017-01-18 09:37 UTC, vira-lytvyn commented on README.md
> +### To run dev envoirement follow instructions below:
Do you mean that these steps describe how to run up app locally?

2017-01-18 09:49 UTC, vira-lytvyn commented
*just a note: it is nice to mention what exactly were modified/deleted/implemented in a specific commit description in order to simplify history processing.
For instance, for this commit, you may use something like 'Add an instruction to readme about how to run the  app locally.'

2017-01-18 10:43 UTC, vira-lytvyn reviewed
I've left some comment and requested a change.
Please process these before merging the current PR.

2017-01-18 20:58 UTC, GAndriyS commented on README.md
> +### To run dev envoirement follow instructions below:
yup

2017-01-18 21:09 UTC, GAndriyS commented
I've added license file to repo. Check it out pls,

2017-01-19 09:02 UTC, vira-lytvyn approved these changes

2017-01-19 09:02 UTC, vira-lytvyn commented on README.md
> +### To run dev envoirement follow instructions below:
then you have to write this) from your description people may think that this is an instruction on how to set up the development environment
with the documentation you need to be precise and very careful - you don't know who and when will use it and what experience he has

2017-01-19 09:03 UTC, vira-lytvyn approved these changes
Greate!

2017-01-20 08:59 UTC, merged